### ISSUE TITLE
Vaga Designer (Web/Mobile/Gráfico)

### ISSUE THREAD

**Issue by amarildolucas** [usekamba/vagas#4]
# Sobre a Kamba:

- Visite: https://www.linkedin.com/company/usekamba
- Leia antes: https://github.com/usekamba/vagas

## Responsabilidades

- Realizar pesquisas de produto e elaborar processos criativos com os nossos usuários
- Fazer propostas e participar na experimentação de MVPs
- Criar wireframes, fluxos, protótipos e identidade visual de produtos móveis e web
- Realizar testes de usabilidade continuamente
- Realizar a documentação e entrega para os desenvolvedores e apoiar no processo de implementação com testes
- Acompanhar funcionalidades lançadas e os resultados de entregas realizadas. Iterar sobre os designs criados
- Criar soluções de melhoria para as nossas plataformas móveis
- Participar das decisões de produto

## Requisitos

- Experiência em design de aplicações mobile e web (somos uma empresa mobile first)
- Conhecimento dos processos de design e metodologias da indústria
- Conhecimento de ferramentas de prototipação
- Conhecimento das ferramentas Adobe XD ou Sketch, Envision, ou similares
- Portfólio rico em projetos ou experiência similar

**Nota:** Ao se candidatar, lembre-se de cadastrar o seu portfólio.

## Desejável

- Noções e/ou experiência com Front-end
- Noções e/ou experiência com metodologias ágeis

Com o Kamba asseguramos nossos clientes/parceiros a resolver os problemas acima com soluções inteligentes e inovadoras sem estresse ou burocracia, diferente dos meios tradicionais com recursos que ajudam a vender e fazer crescer o seu negócio.

Se você se enquadra nesse perfil desafiador, envie seu CV, LinkedIn e portfólio de projetos para suporte@usekamba.com

**Comment by overlineink** [comment]
Como faz pra submeter meu perfil?
